/**
 * The reviewed snapshot in `japa-catalog/snapshot/`: each practice as packs carry
 * it, with every generated script, one file per practice id. It is the
 * baseline for the version rules: the chanted text can't change without a
 * higher version, and versions never go down. A practice removed from
 * `content/` keeps its snapshot, as the highest version its id reached.
 * See docs/japa/architecture/content-pipeline.md#the-reviewed-snapshot.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { exportSchemas, type Practice } from '../domain'
import { parseDocument, stringify } from 'yaml'

import { canonicalJson } from './canonical'
import { readContentTree } from './files'
import { practicePath } from './layout'
import { firstLine, type ContentIssue } from './parse'

const HEADER =
  '# Generated by `npm run content:build` from content/. Review it; never edit it by hand.\n'

const FOLDER = 'practices'
const EXTENSION = '.yaml'

/** Keyed by the practice id alone, so moving a practice keeps its snapshot. */
export function snapshotPath(practice: Pick<Practice, 'id'>): string {
  return `${FOLDER}/${practice.id}${EXTENSION}`
}

/** The practice as YAML: keys sorted, strings in NFC, long lines never folded. */
export function snapshotYaml(practice: Practice): string {
  const canonical: unknown = JSON.parse(text(canonicalJson(practice)))
  return HEADER + stringify(canonical, { lineWidth: 0, aliasDuplicateObjects: false })
}

/**
 * What breaks the version rules, comparing each practice with its snapshot.
 * Only the chanted text counts: each step's text, words and name in every
 * script, and the number of steps.
 */
export function versionIssues(
  practices: readonly Practice[],
  snapshot: ReadonlyMap<string, Practice>,
): ContentIssue[] {
  return practices.flatMap((practice) => {
    const before = snapshot.get(practice.id)
    const problem = before && versionProblem(practice, before)
    return problem ? [{ file: practicePath(practice), path: ['version'], message: problem }] : []
  })
}

function versionProblem(practice: Practice, before: Practice): string | null {
  if (practice.version < before.version) {
    return `Versions only go up: the snapshot is at version ${before.version}`
  }
  if (practice.version > before.version) return null

  const bump = `make it version ${before.version + 1}`
  const [now, then] = [practice.steps.length, before.steps.length]
  if (now !== then) {
    return `Has ${now} steps; the snapshot of version ${before.version} has ${then}: ${bump}`
  }
  if (chanted(practice) !== chanted(before)) {
    return `The chanted text differs from the snapshot of version ${before.version}: ${bump}`
  }
  return null
}

/** The chanted text, in a form two practices can be compared by. */
function chanted(practice: Practice): string {
  return text(canonicalJson(practice.steps.map(({ text, words, name }) => ({ text, words, name }))))
}

export interface SnapshotRead {
  snapshot: Map<string, Practice>
  /** File paths are relative to the snapshot root. */
  issues: ContentIssue[]
}

/** Every practice in the snapshot. A missing folder is an empty snapshot. */
export function readSnapshot(root: string): SnapshotRead {
  const snapshot = new Map<string, Practice>()
  const issues: ContentIssue[] = []
  if (!existsSync(root)) return { snapshot, issues }

  for (const { path, text: yaml } of readContentTree(root)) {
    const result = readPractice(yaml, path)
    if (result.ok) snapshot.set(result.practice.id, result.practice)
    else issues.push({ file: path, ...result.issue })
  }
  return { snapshot, issues }
}

type Read = { ok: true; practice: Practice } | { ok: false; issue: Omit<ContentIssue, 'file'> }

/** The practice in one snapshot file, or what is wrong with it. */
function readPractice(yaml: string, path: string): Read {
  const fail = (message: string, at: Omit<ContentIssue, 'file' | 'message'> = { path: [] }) =>
    ({ ok: false, issue: { ...at, message } }) as const

  const name = /^practices\/([^/]+)\.yaml$/.exec(path)?.[1]
  if (name === undefined) return fail('Not a snapshot file: expected `practices/<id>.yaml`')

  const doc = parseDocument(yaml, { uniqueKeys: true })
  const [error] = doc.errors
  if (error) return fail(firstLine(error.message), { path: [], line: error.linePos?.[0].line })

  const parsed = exportSchemas.practice.safeParse(doc.toJS())
  if (!parsed.success) {
    const [issue] = parsed.error.issues
    return fail(`Not a practice: ${issue!.message}`, { path: issue!.path })
  }
  const practice = parsed.data as Practice
  if (practice.id !== name) {
    return fail(`The id is \`${practice.id}\`, but the file is named \`${name}${EXTENSION}\``)
  }
  return { ok: true, practice }
}

/** Writes each practice's snapshot. Snapshots of other practices stay. */
export function writeSnapshot(root: string, practices: readonly Practice[]): void {
  mkdirSync(join(root, FOLDER), { recursive: true })
  for (const practice of practices) {
    writeFileSync(join(root, snapshotPath(practice)), snapshotYaml(practice))
  }
}

const text = (bytes: Uint8Array) => new TextDecoder().decode(bytes)
